from fastapi import FastAPI
from pydantic import BaseModel


class NodeInferenceRequest(BaseModel):
    """Inference payload accepted by a provider node."""

    model: str
    prompt: str


class NodeInferenceResponse(BaseModel):
    """Text generated by a provider node."""

    response: str


def create_app() -> FastAPI:
    """Build the provider-node application."""
    app = FastAPI(title="CollectiveCompute Provider Node", version="0.1.0")

    @app.post("/inference")
    async def inference(  # pyright: ignore[reportUnusedFunction]
        payload: NodeInferenceRequest,
    ) -> NodeInferenceResponse:
        # Model download and llama.cpp execution will be added behind this stable boundary.
        return NodeInferenceResponse(
            response=f"Provider node received prompt for {payload.model}: {payload.prompt}"
        )

    return app


app = create_app()
